- hosts: all 

  vars:
    ansible_user: Administrator
    ansible_password: Pv5v2lk10@
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
  - name: Install IIS
    win_feature:
        name: web-server
        include_management_tools: yes
        include_sub_features: yes
        state: present

  - name: Copy files to wwwroot
    win_copy:
      src: Front
      dest: C:\inetpub\wwwroot\Front
      force: yes

  - name: Copy files to wwwroot
    win_copy:
      src: Back
      dest: C:\inetpub\wwwroot\Back
      force: yes
  
  - name: Copy files to wwwroot
    win_copy:
      src: Back
      dest: C:\inetpub\wwwroot\Back
      force: yes

  - name: install net core iis hosting module with no frameworks
    win_chocolatey:
      name: "dotnetcore-windowshosting"
      version: "3.1.0"
      install_args: "OPT_NO_RUNTIME=1 OPT_NO_SHAREDFX=1 OPT_NO_X86=1 OPT_NO_SHARED_CONFIG_CHECK=1"
      state: present
    notify: restart IIS

  - name: Create logging directory
    win_file:
        path: c:\logs
        state: directory

  handlers:
    - name: restart IIS
      win_shell: '& {iisreset}'